[package]
name = "bridgetest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# use bleeding-edge azalea
azalea = { git = "https://github.com/azalea-rs/azalea" }
azalea-client = { git = "https://github.com/azalea-rs/azalea" }
azalea-protocol = { git = "https://github.com/azalea-rs/azalea" }
azalea-world = { git = "https://github.com/azalea-rs/azalea" }
bytes = "1.5.0"
chrono = "0.4.34"
config = "0.14.0"
dirs = "5.0.1"
minetest-protocol = "0.1.4"
reqwest = { version = "0.11.24", features = ["blocking", "json"] }
tokio = "1.36.0"
zip-extract = "0.1.3"
