[package]
name = "bridgetest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
mc-varint = "0.1.1"
minecraft-varint = "0.2.0"
minetest-protocol = "0.1.4"
tokio = "1.36.0"
