[package]
name = "bridgetest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea = "0.9.0"
azalea-client = "0.9.0"
azalea-protocol = "0.9.0"
azalea-world = "0.9.0"
bytes = "1.5.0"
chrono = "0.4.34"
minetest-protocol = "0.1.4"
tokio = "1.36.0"

# use git version of all the azalea-* stuff
# idk why, it just wont work otherwise
# perhaps crates.io is outdated?
# -- rant incoming --
# all the minecraft protocol packages seem to either be
# unmaintained or very limited in capability.
# azalea is very feature-complete, but it wont compile without this
# horrible mess of a patch section.
[patch.crates-io]
azalea = { path = "./azalea/azalea" }
azalea-auth = { path = "./azalea/azalea-auth" }
azalea-block = { path = "./azalea/azalea-block" }
azalea-brigadier = { path = "./azalea/azalea-brigadier" }
azalea-buf = { path = "./azalea/azalea-buf" }
azalea-chat = { path = "./azalea/azalea-chat" }
azalea-client = { path = "./azalea/azalea-client" }
azalea-core = { path = "./azalea/azalea-core" }
azalea-crypto = { path = "./azalea/azalea-crypto" }
azalea-entity = { path = "./azalea/azalea-entity" }
azalea-inventory = { path = "./azalea/azalea-inventory" }
azalea-language = { path = "./azalea/azalea-language" }
azalea-physics = { path = "./azalea/azalea-physics" }
azalea-protocol = { path = "./azalea/azalea-protocol" }
azalea-registry = { path = "./azalea/azalea-registry" }
azalea-world = { path = "./azalea/azalea-world" }
